name: "MainZone Text Workflow"
on:
  push:
    branches:
      - workflow-mainzone
env:
  WORKSPACE: $GITHUB_WORKSPACE
jobs:
  MainZone:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run:
          python -m pip install --upgrade pip
          pip install lxml
      - name: "Extract text from files' MainZone"
        run:
          echo ${{ github.repository }}