name: "MainZone Text Workflow"
on:
  push:
    branches:
      - workflow-mainzone
jobs:
  MainZone:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install lxml
      - name: "Extract and collate text from files' MainZones"
        run: |
          python mainZone.py ./data/*
      - name: "Commit generated text files to ./data/"
        if: github.ref == 'refs/heads/main'
        run: |
          git add ./data/*.txt
          git commit -m "Generate text files of documents' MainZone text"
          git push
      - uses: rymndhng/release-on-push-action@master
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        with:
          bump_version_scheme: patch
          use_github_release_notes: true

