name: "MainZone Text Workflow"
on:
  push:
    branches:
      - workflow-mainzone
jobs:
  MainZone:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run:
          python -m pip install --upgrade pip
          pip install lxml
      - name: "Extract text from files' MainZones"
        run:
          echo ${{ jobs.github.job.steps.working-directory }}
          # Relative file path of the directory.
          # The directory name should be equal to the document's Archival Resource Key (ark)
          # ex. bpt6k107371t/